sudo: false
language: node_js
node_js:
  - 12.10.0
env:
  global:
    - YARN_VERSION=1.17.3

before_install:
  - export PATH="$HOME/.yarn/bin:$PATH"
  - |
    if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
    fi

install:
  - yarn install --pure-lockfile

script:
  - yarn run eslint
  - yarn run type-check
  - yarn run test
  - yarn run build
  # Runtime Verify
  - git rev-parse HEAD > out/_version && ls -al out/

after_success:
  - ./node_modules/.bin/codecov

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  local_dir: out
  on:
    tags: true

cache:
  yarn: true
  directories:
    - '~/.yarn'
    - node_modules

notifications:
  email:
    - evenchange4@gmail.com
